<?php

########################################################################
# Extension Manager/Repository config file for ext: "solr_boutique"
#
# Auto generated by Extension Builder 2012-01-10
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

/**
* ext_emconf file for solr_boutique
*
* @package TYPO3
* @subpackage tx_solr_boutique
* @author Denis Sinner <denis.sinner@dkd.de>
*/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Solr Boutique',
	'description' => 'Shop data example for Solr',
	'category' => 'plugin',
	'author' => 'Denis Sinner',
	'author_email' => 'denis.sinner@dkd.de',
	'author_company' => 'dkd Internet Service GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '4.5.0-0.0.0',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>